# Generated by Django 4.1.2 on 2022-11-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand_s',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='product_s',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='brand_s',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product_s',
            name='image',
            field=models.TextField(),
        ),
    ]
