# Generated by Django 4.1.2 on 2022-11-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_brand_s_options_alter_product_s_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_s',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
