# Generated by Django 4.1.2 on 2022-11-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_s_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand_s',
            name='name',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
