# Generated by Django 4.1.2 on 2022-11-09 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_brand_s_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_s',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.brand_s'),
        ),
    ]
