# Generated by Django 4.1.2 on 2022-11-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_s_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand_s',
            name='image2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product_s',
            name='image2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='brand_s',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product_s',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product_s',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
