# Generated by Django 4.1.3 on 2022-12-05 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_refacroting_products'),
        ('cart', '0001_create_order_order_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='product',
        ),
        migrations.AddField(
            model_name='orderline',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.position'),
            preserve_default=False,
        ),
    ]
