# Generated by Django 4.1.3 on 2022-12-05 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_change_product_to_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255)),
                ('country', models.CharField(choices=[('russia', 'Россия'), ('belarus', 'Беларусь'), ('Kazakhstan', 'Казахстан')], default='russia', max_length=255, verbose_name='Страна')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('additional', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='type_payment',
            field=models.CharField(choices=[('card', 'Оплата картой'), ('cash', 'Наличиными при получении')], default='card', max_length=100, verbose_name='Тип оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='contact_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.contactinformation'),
        ),
    ]
